#!/usr/bin/env bash
#
# deploy.sh — Deploy folio-report-explorer on a bare-metal RHEL server.
#
# The repo itself lives at /var/www/html/folio-report-explorer/ and IS the
# web root for the app. Built frontend assets, the api/ symlink, and .htaccess
# all live at the repo root level.
#
# Usage:
#   cd /var/www/html/folio-report-explorer
#   bash deploy.sh
#
# Prerequisites:
#   - PHP 7.2+ with pdo_pgsql, pdo_mysql, curl, mbstring
#   - Node.js 18+
#   - MySQL/MariaDB with the app database created (see mysql/init.sql)
#   - Apache serving /var/www/html with AllowOverride All
#   - A .env file in this directory (copy from .env.example)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Load .env ──────────────────────────────────────────────────────
if [ ! -f .env ]; then
    echo "ERROR: .env file not found. Copy .env.example to .env and fill in values."
    exit 1
fi
set -a
source .env
set +a

# Defaults
APP_BASE_PATH="${APP_BASE_PATH:-}"
VITE_BASE_PATH="${VITE_BASE_PATH:-/}"

echo "=== Folio Report Explorer Deploy ==="
echo "  Repo/Web root: $SCRIPT_DIR"
echo "  Base path:     ${APP_BASE_PATH:-/ (root)}"
echo ""

# ── 1. Pull latest code ────────────────────────────────────────────
echo "→ Pulling latest code..."
git pull origin main

# ── 2. Install Composer (local phar) if needed ─────────────────────
if [ ! -f composer.phar ]; then
    echo "→ Installing Composer..."
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --quiet
    rm composer-setup.php
fi

# ── 3. Install PHP dependencies ───────────────────────────────────
echo "→ Installing backend dependencies..."
cd backend
php "$SCRIPT_DIR/composer.phar" install --no-dev --optimize-autoloader --no-interaction 2>&1 | tail -3
cd "$SCRIPT_DIR"

# ── 4. Build frontend ─────────────────────────────────────────────
echo "→ Installing frontend dependencies..."
cd frontend
npm ci --ignore-scripts 2>&1 | tail -3

echo "→ Building frontend (base path: $VITE_BASE_PATH)..."
VITE_BASE_PATH="$VITE_BASE_PATH" npx vite build 2>&1 | tail -5
cd "$SCRIPT_DIR"

# ── 5. Copy built frontend into repo root ─────────────────────────
echo "→ Copying frontend build to repo root..."

# Copy index.html to repo root
cp frontend/dist/index.html "$SCRIPT_DIR/index.html"

# Copy assets directory
rm -rf "$SCRIPT_DIR/assets"
cp -r frontend/dist/assets "$SCRIPT_DIR/assets"

# Copy any other static files from dist (favicon, etc.)
for f in frontend/dist/*; do
    fname=$(basename "$f")
    if [ "$fname" != "index.html" ] && [ "$fname" != "assets" ]; then
        cp -r "$f" "$SCRIPT_DIR/$fname"
    fi
done

# Create api/ symlink pointing to backend/web/ (if not already there)
if [ ! -L "$SCRIPT_DIR/api" ]; then
    ln -s "$SCRIPT_DIR/backend/web" "$SCRIPT_DIR/api"
fi

# ── 6. Ensure writable directories ────────────────────────────────
echo "→ Setting permissions..."
mkdir -p backend/runtime/cache backend/runtime/logs
chmod -R 775 backend/runtime
chmod 775 backend/data

# Create settings.json if it doesn't exist (will be populated via the web UI)
if [ ! -f backend/data/settings.json ]; then
    echo '{}' > backend/data/settings.json
fi
chmod 664 backend/data/settings.json

# ── 7. Load .env vars for PHP (create a runtime env loader) ───────
ENV_PHP="$SCRIPT_DIR/backend/config/env.php"
cat > "$ENV_PHP" << 'ENVPHP'
<?php
/**
 * Auto-generated by deploy.sh — loads .env values into PHP environment.
 * This file is read by the Yii2 entry point on bare-metal deploys.
 */
$envFile = dirname(dirname(__DIR__)) . '/.env';
if (file_exists($envFile)) {
    $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (strpos($line, '=') === false) continue;
        list($key, $value) = explode('=', $line, 2);
        $key = trim($key);
        $value = trim($value);
        if (!getenv($key)) {
            putenv("$key=$value");
            $_ENV[$key] = $value;
            $_SERVER[$key] = $value;
        }
    }
}
ENVPHP
echo "→ Generated env.php loader"

# ── 8. Generate JWT secret if not set ──────────────────────────────
if ! grep -q '^JWT_SECRET=' .env 2>/dev/null; then
    JWT_SECRET=$(php -r 'echo bin2hex(random_bytes(32));')
    echo "JWT_SECRET=$JWT_SECRET" >> .env
    echo "→ Generated JWT_SECRET and added to .env"
fi

# ── 9. Run database migrations ─────────────────────────────────────
echo "→ Running migrations..."
MYSQL_HOST="${MYSQL_HOST:-localhost}"
MYSQL_CMD="mysql -h $MYSQL_HOST -u ${MYSQL_USER:-folio_app} -p${MYSQL_PASSWORD:-folio_app_pass} ${MYSQL_DATABASE:-folio_report_explorer}"

# Apply each migration SQL file in order
for migration in mysql/migrations/*.sql; do
    if [ -f "$migration" ]; then
        echo "  Applying $(basename "$migration")..."
        $MYSQL_CMD < "$migration" 2>/dev/null || true
    fi
done

# ── 10. Seed database (idempotent — uses REPLACE INTO) ─────────────
if [ "${SEED_DB:-false}" = "true" ]; then
    echo "→ Seeding database..."

    $MYSQL_CMD < mysql/init.sql 2>/dev/null || true
    $MYSQL_CMD < mysql/seed_reports.sql
    $MYSQL_CMD < mysql/seed_training_hints.sql
    $MYSQL_CMD < mysql/seed_saved_queries.sql
    echo "  Loaded: reports, training hints, saved queries"
fi

# ── Done ───────────────────────────────────────────────────────────
echo ""
echo "=== Deploy complete! ==="
echo "  URL: https://$(hostname)/${APP_BASE_PATH#/}"
echo ""
echo "  First deploy? Run with SEED_DB=true to load all data:"
echo "    SEED_DB=true bash deploy.sh"
echo ""
echo "  Auth setup: admin/.htaccess handles Shibboleth protection."
echo "  Ensure mod_shib is loaded and Apache allows .htaccess overrides."
echo ""
echo "  Ensure these are set in .env:"
echo "    JWT_SECRET=...          (auto-generated on first deploy)"
echo "    VITE_AUTH_ENABLED=true  (enables frontend auth)"
echo ""
echo "  Data cleanup (add to cron):"
echo "    0 3 * * 0 cd $SCRIPT_DIR && php backend/yii cleanup/run"
echo ""
