#!/usr/bin/env bash
#
# deploy.sh — Deploy folio-report-explorer on a bare-metal RHEL server.
#
# Usage:
#   cd /opt/folio-report-explorer
#   bash deploy.sh
#
# Prerequisites:
#   - PHP 7.2+ with pdo_pgsql, pdo_mysql, curl, mbstring
#   - Node.js 18+
#   - MySQL/MariaDB with the app database created (see mysql/init.sql)
#   - Apache serving /var/www/html with AllowOverride All
#   - A .env file in this directory (copy from .env.example)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Load .env ──────────────────────────────────────────────────────
if [ ! -f .env ]; then
    echo "ERROR: .env file not found. Copy .env.example to .env and fill in values."
    exit 1
fi
set -a
source .env
set +a

# Defaults
APP_BASE_PATH="${APP_BASE_PATH:-}"
VITE_BASE_PATH="${VITE_BASE_PATH:-/}"
WEBROOT="${WEBROOT:-/var/www/html}"
DEPLOY_DIR="${WEBROOT}/${APP_BASE_PATH#/}"

echo "=== Folio Report Explorer Deploy ==="
echo "  Repo:      $SCRIPT_DIR"
echo "  Deploy to: $DEPLOY_DIR"
echo "  Base path: ${APP_BASE_PATH:-/ (root)}"
echo ""

# ── 1. Pull latest code ────────────────────────────────────────────
echo "→ Pulling latest code..."
git pull origin main

# ── 2. Install Composer (local phar) if needed ─────────────────────
if [ ! -f composer.phar ]; then
    echo "→ Installing Composer..."
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --quiet
    rm composer-setup.php
fi

# ── 3. Install PHP dependencies ───────────────────────────────────
echo "→ Installing backend dependencies..."
cd backend
php "$SCRIPT_DIR/composer.phar" install --no-dev --optimize-autoloader --no-interaction 2>&1 | tail -3
cd "$SCRIPT_DIR"

# ── 4. Build frontend ─────────────────────────────────────────────
echo "→ Installing frontend dependencies..."
cd frontend
npm ci --ignore-scripts 2>&1 | tail -3

echo "→ Building frontend (base path: $VITE_BASE_PATH)..."
VITE_BASE_PATH="$VITE_BASE_PATH" npx vite build 2>&1 | tail -5
cd "$SCRIPT_DIR"

# ── 5. Deploy to web root ─────────────────────────────────────────
echo "→ Deploying to $DEPLOY_DIR..."
mkdir -p "$DEPLOY_DIR"

# Copy built frontend assets
cp -r frontend/dist/* "$DEPLOY_DIR/"

# Copy the .htaccess for SPA routing
cp public/.htaccess "$DEPLOY_DIR/.htaccess"

# Create api/ symlink pointing to backend/web/
if [ -L "$DEPLOY_DIR/api" ]; then
    rm "$DEPLOY_DIR/api"
fi
ln -s "$SCRIPT_DIR/backend/web" "$DEPLOY_DIR/api"

# ── 6. Ensure writable directories ────────────────────────────────
echo "→ Setting permissions..."
mkdir -p backend/runtime/cache backend/runtime/logs
chmod -R 775 backend/runtime
chmod 775 backend/data

# Create settings.json if it doesn't exist (will be populated via the web UI)
if [ ! -f backend/data/settings.json ]; then
    echo '{}' > backend/data/settings.json
fi
chmod 664 backend/data/settings.json

# ── 7. Load .env vars for PHP (create a runtime env loader) ───────
ENV_PHP="$SCRIPT_DIR/backend/config/env.php"
cat > "$ENV_PHP" << 'ENVPHP'
<?php
/**
 * Auto-generated by deploy.sh — loads .env values into PHP environment.
 * This file is read by the Yii2 entry point on bare-metal deploys.
 */
$envFile = dirname(dirname(__DIR__)) . '/.env';
if (file_exists($envFile)) {
    $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (strpos($line, '=') === false) continue;
        list($key, $value) = explode('=', $line, 2);
        $key = trim($key);
        $value = trim($value);
        if (!getenv($key)) {
            putenv("$key=$value");
            $_ENV[$key] = $value;
            $_SERVER[$key] = $value;
        }
    }
}
ENVPHP
echo "→ Generated env.php loader"

# ── Done ───────────────────────────────────────────────────────────
echo ""
echo "=== Deploy complete! ==="
echo "  URL: https://$(hostname)/${APP_BASE_PATH#/}"
echo ""
echo "  If this is the first deploy, remember to:"
echo "    1. Run: mysql < mysql/init.sql"
echo "    2. Run: mysql < mysql/seed_reports.sql"
echo "    3. Visit the /setup page to configure FOLIO and Gemini credentials"
echo ""
