CREATE TABLE IF NOT EXISTS ai_report_generations (
    id CHAR(36) PRIMARY KEY,
    conversation_id CHAR(36) NOT NULL,
    parent_generation_id CHAR(36) NULL,
    query_job_id CHAR(36) NULL,
    user_id INT NULL,
    prompt_fingerprint CHAR(16) NOT NULL,
    original_question TEXT NOT NULL,
    follow_up_context JSON NULL,
    response_mode VARCHAR(32) NULL,
    execution_mode ENUM('deterministic','exploratory') NULL,
    route VARCHAR(128) NULL,
    route_reason VARCHAR(255) NULL,
    validation_status ENUM('validated','exhausted','rejected') NULL,
    generated_sql MEDIUMTEXT NULL,
    sql_hash CHAR(64) NULL,
    assumptions_json JSON NULL,
    user_notice_json JSON NULL,
    confidence_evidence_json JSON NOT NULL,
    initial_structure_json JSON NULL,
    final_structure_json JSON NULL,
    provenance_json JSON NOT NULL,
    review_required TINYINT(1) NOT NULL DEFAULT 0,
    review_reasons_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    linked_at DATETIME NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_report_generations_conversation (conversation_id),
    INDEX idx_ai_report_generations_parent (parent_generation_id),
    INDEX idx_ai_report_generations_job (query_job_id),
    INDEX idx_ai_report_generations_user (user_id),
    INDEX idx_ai_report_generations_created (created_at),
    INDEX idx_ai_report_generations_review_required (review_required),
    CONSTRAINT fk_ai_report_generations_parent FOREIGN KEY (parent_generation_id) REFERENCES ai_report_generations(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_report_generations_job FOREIGN KEY (query_job_id) REFERENCES query_jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_report_reviews (
    id CHAR(36) PRIMARY KEY,
    generation_id CHAR(36) NOT NULL UNIQUE,
    status ENUM('pending','in_review','resolved','dismissed') NOT NULL DEFAULT 'pending',
    disposition ENUM('acceptable','assumption_change','deterministic_candidate','generation_defect','data_unavailable','specialist_interpretation') NULL,
    advisory_state ENUM('none','cautioned','superseded') NOT NULL DEFAULT 'none',
    superseded_by_job_id CHAR(36) NULL,
    administrator_notes TEXT NULL,
    reviewed_by INT NULL,
    claimed_at DATETIME NULL,
    resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_report_reviews_status_created (status, created_at),
    INDEX idx_ai_report_reviews_disposition (disposition),
    INDEX idx_ai_report_reviews_advisory_state (advisory_state),
    INDEX idx_ai_report_reviews_reviewed_by (reviewed_by),
    INDEX idx_ai_report_reviews_superseding_job (superseded_by_job_id),
    CONSTRAINT fk_ai_report_reviews_generation FOREIGN KEY (generation_id) REFERENCES ai_report_generations(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_report_reviews_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_report_reviews_superseding_job FOREIGN KEY (superseded_by_job_id) REFERENCES query_jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
